# -*- coding: utf-8 -*-
"""K_means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Abhishekkl14/ATM_machine/blob/main/K_means.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans

X=np.array([[1, 2], [1.5, 1.8], [5, 8], [8, 8], [1, 0.6], [9, 11]])

plt.scatter(X[:, 0], X[:, 1], s=100)
plt.show()

# Applying K-Means Clustering
kmeans = KMeans(n_clusters=2) # We are choosing 2 clusters
kmeans.fit(X)

centroids = kmeans.cluster_centers_
labels = kmeans.labels_

colors = ['g', 'r']

for i in range(len(X)):
    plt.scatter(X[i][0], X[i][1], color=colors[labels[i]], s=100)
    plt.scatter(centroids[:, 0], centroids[:, 1], color='b', marker='x', s=200) # Centroids
    plt.show()



